# Logo generator: renders docs/logo.png with this library itself — the
# title "freetype.cr" (DejaVu Sans Bold, hinted) and the caption
# "( generated by library )" (DejaVu Sans), rasterized by TT::HintedFace
# + Ftrender and packed into a PNG via Compress::Zlib.
#
#   crystal run --release spec/gen_logo.cr [-- output.png]
#
# Without arguments the output goes to docs/logo.png in the repo root.

require "compress/zlib"
require "../src/freetype-cr"

FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FONT_REG  = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

TITLE  = "freetype.cr"
CAPTION = "( generated by library )"
TITLE_PX  = 64
CAPTION_PX = 18
MARGIN_X = 8
MARGIN_TOP = 8
GAP = 20 # baseline gap between title and caption

# indigo -> cyan across the title, gray caption
def title_color(x : Int32, w : Int32) : {Int32, Int32, Int32}
  t = w <= 1 ? 0.0_f64 : x.to_f64 / (w - 1)
  r = (67 + ((14 - 67) * t)).round.to_i32.clamp(0, 255)   # 0x43 -> 0x0E
  g = (56 + ((165 - 56) * t)).round.to_i32.clamp(0, 255)  # 0x38 -> 0xA5
  b = (202 + ((233 - 202) * t)).round.to_i32.clamp(0, 255) # 0xCA -> 0xE9
  {r, g, b}
end

CAPTION_COLOR = {107, 114, 128} # #6B7280

# Baked text run: glyph bitmaps with 26.6 pen offsets, plus the total
# advance in 26.6.
class TextRun
  getter items : Array({Int64, Ftrender::GlyphBitmap}) # {pen_x 26.6, bitmap}
  getter width26 : Int64

  def initialize(face : TT::HintedFace, text : String)
    @items = [] of {Int64, Ftrender::GlyphBitmap}
    font = face.font
    kern_scale = (face.px * 64) // font.upem
    pen = 0_i64
    prev_gid = -1
    text.each_char do |ch|
      code = ch.ord
      gid = font.glyph_index(code) # space is a real glyph: empty outline
      if prev_gid >= 0
        pen += (font.kerning(prev_gid, gid) * kern_scale).to_i64
      end
      g = face.load_glyph(gid)
      bmp = Ftrender.render_glyph(
        Ftgrays::Outline.new(g.xs, g.ys, g.tags, g.contours))
      @items << {pen, bmp}
      pen += g.advance
      prev_gid = gid
    end
    @width26 = pen
  end
end

class TT::HintedFace
  getter px # expose for kern scaling above
end

# --- compose onto an RGBA canvas ---------------------------------------

class Canvas
  getter w : Int32
  getter h : Int32
  getter data : Array(UInt8) # RGBA, w*h*4

  def initialize(@w, @h)
    @data = Array(UInt8).new(@w * @h * 4, 0_u8)
  end

  def blend(x : Int32, y : Int32, cov : UInt8, r : Int32, g : Int32, b : Int32) : Nil
    return if x < 0 || y < 0 || x >= @w || y >= @h
    a = cov.to_i32
    return if a == 0
    i = (y * @w + x) * 4
    # coverage over transparent background: alpha = a, color straight
    @data[i] = r.to_u8!
    @data[i + 1] = g.to_u8!
    @data[i + 2] = b.to_u8!
    @data[i + 3] = Math.max(a, @data[i + 3].to_i32).to_u8!
  end

  def draw_run(run : TextRun, pen_x_px : Int32, baseline : Int32,
               color : (Int32, Int32) -> {Int32, Int32, Int32}) : Nil
    run.items.each do |pen26, bmp|
      next if bmp.width <= 0
      dst_x = pen_x_px + (pen26 >> 6).to_i32! + bmp.left
      dst_y = baseline - bmp.top
      bmp.height.times do |row|
        y = dst_y + row
        bmp.width.times do |col|
          cov = bmp.buffer[row * bmp.width + col]
          next if cov == 0
          r, g, b = color.call(dst_x + col, @w)
          blend(dst_x + col, y, cov, r, g, b)
        end
      end
    end
  end
end

# --- minimal PNG writer (RGBA, filter 0) --------------------------------

CRC_POLY = 0xEDB8_8320_u32

def crc32(buf : Bytes, seed : UInt32 = 0_u32) : UInt32
  crc = seed ^ 0xFFFF_FFFF_u32
  buf.each do |b|
    crc ^= b
    8.times do
      crc = (crc & 1) == 1 ? ((crc >> 1) ^ CRC_POLY) : (crc >> 1)
    end
  end
  crc ^ 0xFFFF_FFFF_u32
end

def png_chunk(io : IO, type : String, data : Bytes) : Nil
  io.write_bytes(data.size.to_u32, IO::ByteFormat::BigEndian)
  type_slice = type.to_slice
  io.write(type_slice)
  io.write(data)
  io.write_bytes(
    crc32(data, crc32(type_slice)).to_u32, IO::ByteFormat::BigEndian)
end

def write_png(path : String, canvas : Canvas) : Nil
  File.open(path, "w") do |f|
    f.write(Bytes[0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
    ihdr = Bytes.new(13)
    io = IO::Memory.new(ihdr)
    io.write_bytes(canvas.w.to_u32, IO::ByteFormat::BigEndian)
    io.write_bytes(canvas.h.to_u32, IO::ByteFormat::BigEndian)
    ihdr[8] = 8_u8  # bit depth
    ihdr[9] = 6_u8  # color type RGBA
    ihdr[10] = 0_u8 # compression
    ihdr[11] = 0_u8 # filter
    ihdr[12] = 0_u8 # interlace
    png_chunk(f, "IHDR", ihdr)
    raw = Bytes.new(canvas.h * (1 + canvas.w * 4))
    pos = 0
    canvas.h.times do |y|
      raw[pos] = 0_u8 # filter: none
      pos += 1
      canvas.w.times do |x|
        i = (y * canvas.w + x) * 4
        raw[pos] = canvas.data[i]
        raw[pos + 1] = canvas.data[i + 1]
        raw[pos + 2] = canvas.data[i + 2]
        raw[pos + 3] = canvas.data[i + 3]
        pos += 4
      end
    end
    comp = IO::Memory.new
    zw = Compress::Zlib::Writer.new(comp)
    zw.write(raw)
    zw.close
    png_chunk(f, "IDAT", comp.to_slice)
    png_chunk(f, "IEND", Bytes.new(0))
  end
end

# --- bake ----------------------------------------------------------------

bold = TT::HintedFace.new(File.read(FONT_BOLD).to_slice)
bold.set_pixel_size(TITLE_PX)
reg = TT::HintedFace.new(File.read(FONT_REG).to_slice)
reg.set_pixel_size(CAPTION_PX)

title = TextRun.new(bold, TITLE)
caption = TextRun.new(reg, CAPTION)

upem_b = bold.font.upem
asc1 = bold.font.ascender * TITLE_PX // upem_b
desc1 = -bold.font.descender * TITLE_PX // upem_b
upem_r = reg.font.upem
asc2 = reg.font.ascender * CAPTION_PX // upem_r
desc2 = -reg.font.descender * CAPTION_PX // upem_r

width = MARGIN_X * 2 + Math.max(title.width26 >> 6, caption.width26 >> 6)
baseline1 = MARGIN_TOP + asc1
baseline2 = baseline1 + desc1 + GAP + asc2
height = baseline2 + desc2 + 8

canvas = Canvas.new(width, height)
canvas.draw_run(title, MARGIN_X, baseline1, ->title_color(Int32, Int32))
cap_x = MARGIN_X + ((title.width26 - caption.width26) >> 6).to_i32 // 2
cap_gray = ->(x : Int32, w : Int32) { {107, 114, 128} }
canvas.draw_run(caption, cap_x, baseline2, cap_gray)

out_path = ARGV[0]? || File.join(__DIR__, "..", "docs", "logo.png")
Dir.mkdir_p(File.dirname(out_path))
write_png(out_path, canvas)
puts "#{out_path}: #{width}x#{height} (title #{TITLE_PX}px hinted, caption #{CAPTION_PX}px)"
